### ISSUE TITLE
Hubot On Kik Through Microsoft

### ISSUE THREAD

**Issue by Viper702** [Microsoft/BotFramework-Hubot#1]
Hubot is not responding in Kik with hubot-epichal module. The logs show that the bot is learning "Hello" and various phrases and words but it never replies. Script responses work perfectly. Hubot will respond to messages from various chats but it never seems to listen to any chat on Kik that it's been invited too. It is not actually listening except for its private chat with me. Announce.coffee will not message assigned chats on Kik. Pubsub, rss poller and any scripts that use a room number or subscription fail on Kik. Finally, the bot only posts urls of images and not the image on Kik.

**Comment by maxpert** [comment]
So if I am understanding it correctly, you are able to do one to one chat with your hubot but you are not receiving messages on Kik group?

**Comment by maxpert** [comment]
Are you still facing this issue? If yes let me know.
