### ISSUE TITLE
How can i use this adapter connect to the Skype for bussiness client?

### ISSUE THREAD

**Issue by yuqi17** [Microsoft/BotFramework-Hubot#12]

**Comment by MattSFT** [comment]
You would have to register your bot with botframework at dev.botframework.com. This will let you register the messages endpoint (by default <bot root URL>/api/messages) with botframework so we know how to route your messages. It will also give you the BOTBUILDER_APP_ID and BOTBUILDER_APP_PASSWORD to set on your environment.

You then need the add the Skype for Business channel on the botframework website to your bot. That flow will give you additional information on Skype for Business specifics.

**Comment by yuqi17** [comment]
I  find this [link](https://msdn.microsoft.com/zh-cn/skype/Skype-For-Business-Bot-Framework/docs/overview)  and try to do it,but failed at step 2:

- Import-PSSession (New-CsOnlineSession -Credential (Get-Credential))  
did you test it ok?

**Comment by MattSFT** [comment]
What is the error you get?

**Comment by yuqi17** [comment]
The error is:

- Get-CsAccessToken : parsing_wstrust_response_failed: Parsing WS-Trust response failed

**Comment by MattSFT** [comment]
Are you sure that your account is a Tenant Administrator account?

**Comment by yuqi17** [comment]
I think so,my account is granted the administrator by my Project Manager.

**Comment by MattSFT** [comment]
Can you confirm that you have been granted this role? https://support.office.com/en-us/article/About-the-Skype-for-Business-admin-role-aeb35bda-93fc-49b1-ac2c-c74fbeb737b5

I think that is the role you need. If you can confirm you have it then I think the next course of action would be to post to the skype for business folks asking for help.

**Comment by yuqi17** [comment]
I will talk with you using e-mail.my e-mail address is  qi.yu.o@nio.com

**Comment by yuqi17** [comment]
Thanks Matt,I receive you email.And I think it 's something with my Skype for Bussiness permissions too.I will try it again.
