### ISSUE TITLE
Noob issue with getting botframework back to hubot

### ISSUE THREAD

**Issue by rajien2** [Microsoft/BotFramework-Hubot#13]
I apologize to all the extreamly smart people here on this project for such a rudimentary question but i've spend the past day and a half working on this... I'm attempting to connect my hubot sever to our ms-teams server. I am getting hung up on getting my chats back to hubot. 

Currently when I use the test button on dev.botframework.com I do see a chat message coming up on teams as my incoming webhook. Now the issue is creating a custom bot its asking for a Callback URL, from what I understand is this gets my chats back to the framework. From what ive been able to find it should be #botname.azurewebsites.net/api/messages. However for my bot scentsy_chronos this returns a page not found. Am I missing a set to get my bot its own url? 

When starting hubot on my windows server I do get:

[Sat Aug 05 2017 23:08:17 GMT-0700 (Pacific Daylight Time)] INFO hubot-botframew
ork-adapter: Adapter loaded. Using appId 072de5c6-80a4-489a-8377-7e3afccd7385
[Sat Aug 05 2017 23:08:17 GMT-0700 (Pacific Daylight Time)] INFO hubot-botframew
ork-adapter: Adapter running.
[Sat Aug 05 2017 23:08:19 GMT-0700 (Pacific Daylight Time)] INFO hubot-redis-bra
in: Discovered redis from REDIS_URL environment variable
[Sat Aug 05 2017 23:08:19 GMT-0700 (Pacific Daylight Time)] INFO hubot-redis-bra
in: Data for export%20REDIS_URL=redis:/:######@10.1.10.12:16379/prefix brain r
etrieved from Redis

So I would believe its making the connection into the framework to get the messages but getting them there is the issue... Any help would be greatly appreciated.

Thanks
Cody

**Comment by MattSFT** [comment]
Sounds like you are using the custom bot option in Teams instead of sideloading an app is that right? If so try to make a quick manifest for your bot and sideload it as an App. There's some docs here:
https://msdn.microsoft.com/en-us/microsoft-teams/sideload
