### ISSUE TITLE
I find an error when i try to run a command line for setting skype for bussiness

### ISSUE THREAD

**Issue by yuqi17** [Microsoft/BotFramework-Hubot#14]
###  Import-PSSession (New-CsOnlineSession -Credential (Get-Credential))

# New-CsOnlineApplicationEndpoint -ApplicationId 4a4b1429-64d7-417b-8d74-9541c3e3da1e  -Name niobot sip:qi.yu.o@nio.com

Enterprise voice directory service failed.

    + CategoryInfo          : NotSpecified: (Microsoft.Rtc.M...Directory service discovery failed. Please try again later. :PlatformServiceCmdletException) [New-CsOnlineApplicationEndpoint], BvdCmdletException

    + FullyQualifiedErrorId : Could not instantiate TrustedApplicationEndpointManager,Microsoft.Rtc.Management.Hosted.PlatformService.NewPlatformServiceAppEndpointConfigCmdlet

    + PSComputerName        : admin0g.online.partner.lync.cn

**Comment by yuqi17** [comment]
https://blog.thoughtstuff.co.uk/2017/05/how-to-enable-your-bot-framework-bot-on-skype-for-business-and-how-i-finally-got-it-working/   This is a blog I found.and I am wrong with running command the line: 

- New-CsOnlineApplicationEndpoint  -ApplicationId 4a4b1429-64d7-417b-8d74-9541c3e3da1e -Name niobot sip:qi.yu.o@nio.com

**Comment by MattSFT** [comment]
These are very skype for business specific failures in adding a bot and not hubot-botframework related. The contributors here don't have much experience with skype for business so it would be much better to post your question here on stackoverflow.com and tag it with skype-for-business (https://stackoverflow.com/questions/tagged/skype-for-business).

Once you actually have your bot registered, if there are any questions with processing commands and talking to hubot, etc we can certainly help here.

**Comment by MattSFT** [comment]
We haven't heard back in over a month so assuming this issue got resolved. Please raise a new one if you still need help.
