### ISSUE TITLE
How to use this adapter?

### ISSUE THREAD

**Issue by nichida** [Microsoft/BotFramework-Hubot#24]
Please tell me how to use this adapter.

HUBOT → Azure Bot service [Bot channel registration] → Microsoft team

I think that I can connect it and use it.

Is there a way to use it?

**Comment by MattSFT** [comment]
Yes it will work with bot framework. you will need to expose your bot to the internet because the bot framework channel registration requires a public messages endpoint. Once you do that it should work fine.

**Comment by nichida** [comment]
Thank you!

It is like the structure as below.

Microsoft teams → Azure Bot service [Bot channel registration] (→ WEB HOOK?) → This adapter → HUBOT → Microsoft teams ...

At first I did not understand that HUBOT is awaiting WEBHOOK.

This is very useful!

**Comment by MattSFT** [comment]
Yes that is how the information flows into your bot. Glad I could help.
