### ISSUE TITLE
Is it still working with MS Teams?

### ISSUE THREAD

**Issue by kstevena** [Microsoft/BotFramework-Hubot#27]
I'm wondering if this approach is still working with MS Teams. Because trying to follow the documentation and when going to https://dev.botframework.com/bots/new and trying to create new bot, when submiting the form it always fails like this:

- first time the form is submited there is an unclear popup displaying someting like "CorrelationID: XYZ"
- if retrying it indicates that the MsaAppId is already being used

**Comment by MattSFT** [comment]
This is due to a regression in Bot Framework. The team is working to resolve it. You can also register the bot in the azure portal for Teams and it should work as well.

**Comment by kstevena** [comment]
thanks @MattSFT for the feedback, i was afraid this option was simply not anymore supported.
this morning i got an internal server error, and after a retry the bot was created!
