### ISSUE TITLE
Hubot in channel

### ISSUE THREAD

**Issue by rbuezotordesillas** [Microsoft/BotFramework-Hubot#28]
I am able to add hubot to a conversation in MS teams and interact with it. However when I try to add it as a member in a channel, it will not let me.
Has this happened to anyone else?

**Comment by MattSFT** [comment]
Have you done this step?
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-package

If not, we recommend using the App Studio for Microsoft Teams to create your app package:
https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio

**Comment by angegar** [comment]
@MattSFT  @rbuezotordesillas  I have the same issue when i go in a channel i can interact with my bot however my bot does not listen the channel.

**Comment by MattSFT** [comment]
bots do not have access to messages in Teams where they are not explicitly @ mentioned

**Comment by leonardochaia** [comment]
@MattSFT this may be a recurrent issue. Maybe we should add this to the readme somewhere.

**Comment by MattSFT** [comment]
I added this section:
https://github.com/Microsoft/BotFramework-Hubot/blob/master/README.md#common-differences-in-hubot-running-in-slack-hipchat-other-chat-platforms-and-ms-teams
