### ISSUE TITLE
Doesn't support Image Embeds

### ISSUE THREAD

**Issue by aliasfalse** [Microsoft/BotFramework-Hubot#3]
This will not embed images, for example, `/pug me`, it will just send the link.

**Comment by maxpert** [comment]
I am already considering to add support for developers to pass schema compatible objects in response. This will allow users to not only send attachments but also some adaptive cards etc.

**Comment by billbliss** [comment]
I have found a solution for this (technically it's quite simple) but I didn't do it very elegantly, so @maxpert is thinking of a more general approach.

**Comment by aliasfalse** [comment]
I have a solution on the custom bot route, but I'm not ready to put it into the wild.

**Comment by billbliss** [comment]
@aliasfalse support for MS Teams is now incorporated and supports images (and card attachments) using the middleware approach @maxpert defined.
