### ISSUE TITLE
Can you please provide a sample

### ISSUE THREAD

**Issue by angegar** [Microsoft/BotFramework-Hubot#30]
Hi, 
I am completly noob in bot and i am struggling to make it works. Can you please add a basic sample in your documentation.

My understanding is that we just need to create a hubot script as documented by hubot containing an endpoint (/api/messages) which will handle the communication with botframework. Thus if i create a bot with the following code :

`robot.router.post('/api/messages', function(req,resp){
data  = req.body
resp.send(data)
}
`

it should work. however in using the test feature in dev.botframework.com i can't send any messages to my bot.

Any help will be great.

++

**Comment by angegar** [comment]
@leonardochaia thank you for your answer, i will see if i can reuse some piece. For now i think my issue is more related with my nginx ingress controller than with the way i configure hubot.

**Comment by MattSFT** [comment]
@angegar you can also use the yeoman generator to build a sample with hubot. For adapter specify 'botframework'

The hubot docs have more info on this https://hubot.github.com/docs/

**Comment by angegar** [comment]
Thank you i finally managed to make it works, i believed that i have to implement the api/messages endpoint when it is made by the adapter. :)
